name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 1.0.4
publish_to: none

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.6.0
  google_maps_flutter_platform_interface: ^2.6.0
  apple_maps_flutter:
    git:
      url: https://github.com/millerf/platform_maps_flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
